language: python
python:
  - "3.5"
  - "3.6"
env:
    - COVERALLS_PARALLEL=true
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=keras2c/

after_script:
  - coveralls
  - cpp-coveralls -i include  

notifications:
  webhooks: https://coveralls.io/webhook	
