language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install:
# add new stuff to requirements file, not here
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest --cov=keras2c/

after_script:
  - coveralls
  - cpp-coveralls -i include  
notifications:

